### ISSUE TITLE
Incompatible with vite

### ISSUE THREAD

**Issue by fc** [davenquinn/cesium-martini#14]
When trying to include `@macrostrat/cesium-martini` in a bare bones Vite project the following error occurs:
```
browser-external:path:9 Module "path" has been externalized for browser compatibility. Cannot access "path.join" in client code.
get @ browser-external:path:9
18:12:23.384 index.cjs:14 Uncaught ReferenceError: __dirname is not defined
    at node_modules/cesium/index.cjs (index.cjs:14:3)
    at __require2 (chunk-7FP5O474.js?v=6ac06d1a:10:50)
    at node_modules/@macrostrat/cesium-martini/dist/index.js (index.cjs:16:1)
    at __require2 (chunk-7FP5O474.js?v=6ac06d1a:10:50)
    at dep:@macrostrat_cesium-martini:1:16
```

You can see this in a very basic repro here (check your browser's dev console): 
https://stackblitz.com/edit/vitejs-vite-pqnxx6?file=package.json,src%2FApp.jsx&terminal=dev

By hacking the cesium module to import the cesium module directly to bypass the error (import cesium using `cesium/Build/Cesium/Cesium` instead of `cesium`), then I see this error:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
    at worker-farm.ts:52:3
    at worker-farm.ts:52:3
    at node_modules/@macrostrat/cesium-martini/dist/index.js (worker-farm.ts:52:3)
    at __require2 (chunk-7FP5O474.js?v=4361fb93:10:50)
    at dep:@macrostrat_cesium-martini:1:16
```

It seems like I can workaround that with this - `yarn add -D regenerator-runtime` then:
```
import 'regenerator-runtime/runtime';
// import cesium-martini module here
```
note: using the `@vitejs/plugin-legacy` didn't appear to work

I _think_ this can be resolved by adding `@babel/plugin-transform-runtime` to your project's babelrc

**Comment by davenquinn** [comment]
Thanks, this is a helpful report. 

I think the first part might be a Cesium issue? There are a few gotchas with bundling Cesium certainly.

I've struggled with the `regeneratorRuntime` issues for a while in a few modules, and I think that I've managed to fix them in a few cases by switching bundling from Rollup to Parcel.js. Not sure if that would work in this case.
